#!/usr/bin/env python3
"""Build the current empty database schema from the reviewed migration chain.

The builder runs MySQL in an isolated, network-disabled Docker container, applies
the historical baseline and migrations, then exports schema only. It never
connects to a developer or production database.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import time
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATABASE = "nyc_review_bootstrap"
PASSWORD = "bootstrap-container-only"
IMAGE = "mysql:8.4"
OUTPUT = ROOT / "src/main/resources/db/bootstrap-schema.sql"
MIGRATIONS = [
    "001_legacy_baseline.sql",
    "002_data_consistency.sql",
    "003_voucher_order_uniqueness.sql",
    "004_nyc_compatibility.sql",
    "005_nyc_domain.sql",
    "006_agent_actions.sql",
    "007_rabbitmq_profile_memory.sql",
    "008_mcp_ui.sql",
    "009_data_provenance.sql",
    "010_map_geospatial.sql",
    "011_real_content.sql",
    "012_shop_enrichment.sql",
    "013_data_quality.sql",
    "014_cleanup_legacy.sql",
    "015_password_auth_registration.sql",
    "016_blog_comment_index.sql",
    "017_shop_review_likes.sql",
]


def run(command: list[str], *, payload: bytes | None = None) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        command,
        cwd=ROOT,
        input=payload,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )


def wait_until_healthy(container: str) -> None:
    deadline = time.monotonic() + 90
    while time.monotonic() < deadline:
        status = run(
            ["docker", "inspect", "--format", "{{.State.Health.Status}}", container]
        ).stdout.decode().strip()
        if status == "healthy":
            return
        if status == "unhealthy":
            raise RuntimeError("bootstrap MySQL container became unhealthy")
        time.sleep(0.5)
    raise TimeoutError("bootstrap MySQL container did not become healthy within 90 seconds")


def normalize_dump(raw: str) -> str:
    schema = re.sub(r" AUTO_INCREMENT=\d+", "", raw)
    forbidden = (
        "legacy_hangzhou_",
        "tb_legacy_archive_state",
        "tb_voucher_order_conflict_archive",
        "CREATE TABLE `tb_sign`",
        "INSERT INTO",
    )
    present = [token for token in forbidden if token in schema]
    if present:
        raise RuntimeError(f"bootstrap schema still contains legacy/data content: {present}")
    required = (
        "CREATE TABLE `tb_user`",
        "CREATE TABLE `tb_shop`",
        "CREATE TABLE `tb_voucher_order`",
        "CREATE TABLE `tb_shop_map_location`",
        "CREATE TABLE `tb_agent_action_audit`",
        "CREATE TABLE `tb_shop_field_observation`",
        "UNIQUE KEY `uk_user_phone` (`phone`)",
        "UNIQUE KEY `uk_voucher_order_user_voucher` (`user_id`,`voucher_id`)",
        "KEY `idx_blog_comments_blog_time` (`blog_id`,`create_time`)",
        "CREATE TABLE `tb_shop_review_like`",
    )
    missing = [token for token in required if token not in schema]
    if missing:
        raise RuntimeError(f"bootstrap schema is missing current contracts: {missing}")
    header = (
        "-- NYC Review current empty database schema.\n"
        "-- Generated by scripts/db/build_bootstrap_schema.py; do not edit manually.\n"
        "-- Runtime datasets and neighborhood projections are imported separately.\n\n"
    )
    return header + schema.strip() + "\n"


def mysql_command(container: str, *, database: bool = True) -> list[str]:
    command = [
        "docker",
        "exec",
        "-i",
        container,
        "mysql",
        "-uroot",
        f"-p{PASSWORD}",
        "--binary-mode=1",
    ]
    if database:
        command.append(DATABASE)
    return command


def apply_sql(container: str, path: Path) -> None:
    run(mysql_command(container), payload=path.read_bytes())


def verify_dataset(container: str, dataset_dir: Path) -> None:
    manifest_path = dataset_dir / "manifest.json"
    dataset_sql = dataset_dir / "mysql_import.sql"
    map_sql = dataset_dir / "p7_neighborhood_import.sql"
    missing = [
        str(path.relative_to(ROOT) if path.is_relative_to(ROOT) else path)
        for path in (manifest_path, dataset_sql, map_sql)
        if not path.is_file()
    ]
    if missing:
        raise FileNotFoundError(f"dataset verification files are missing: {missing}")

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    expected_shops = int(manifest["counts"]["shops"])
    expected_profile = str(manifest["profile"])

    reset_sql = (
        f"DROP DATABASE IF EXISTS `{DATABASE}`;"
        f"CREATE DATABASE `{DATABASE}` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
    ).encode()
    run(mysql_command(container, database=False), payload=reset_sql)
    apply_sql(container, OUTPUT)
    apply_sql(container, dataset_sql)
    apply_sql(container, map_sql)

    query = """
SELECT
  (SELECT COUNT(*) FROM tb_shop),
  (SELECT COUNT(*) FROM tb_shop_type),
  (SELECT COUNT(*) FROM tb_shop_map_location),
  (SELECT COUNT(*) FROM tb_data_import WHERE active = 1),
  (SELECT profile FROM tb_data_import WHERE active = 1 LIMIT 1),
  (SELECT COUNT(*) FROM information_schema.TABLES
     WHERE TABLE_SCHEMA = DATABASE()
       AND (TABLE_NAME LIKE 'legacy_hangzhou_%'
            OR TABLE_NAME IN ('tb_legacy_archive_state', 'tb_sign'))),
  (SELECT COUNT(*) FROM tb_shop_field_observation WHERE provider = 'HMDP_GENERATED');
"""
    output = run(
        mysql_command(container)
        + ["--batch", "--skip-column-names", "--execute", query]
    ).stdout.decode().strip()
    fields = output.split("\t")
    if len(fields) != 7:
        raise RuntimeError(f"unexpected bootstrap verification output: {output!r}")
    shops, shop_types, map_locations, active_imports, profile, legacy, old_provider = fields
    failures = []
    if int(shops) != expected_shops:
        failures.append(f"shops={shops}, expected={expected_shops}")
    if int(shop_types) != 6:
        failures.append(f"shop_types={shop_types}, expected=6")
    if int(map_locations) != expected_shops:
        failures.append(f"map_locations={map_locations}, expected={expected_shops}")
    if int(active_imports) != 1 or profile != expected_profile:
        failures.append(
            f"active_imports={active_imports}, profile={profile!r}, expected={expected_profile!r}"
        )
    if int(legacy) != 0:
        failures.append(f"legacy_tables={legacy}, expected=0")
    if int(old_provider) != 0:
        failures.append(f"HMDP_GENERATED observations={old_provider}, expected=0")
    if failures:
        raise RuntimeError("fresh bootstrap verification failed: " + "; ".join(failures))
    print(
        "Verified fresh bootstrap: "
        f"profile={profile}, shops={shops}, shop_types={shop_types}, map_locations={map_locations}"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--verify-dataset",
        type=Path,
        help="After building the schema, recreate the temporary database and import this dataset plus its map SQL.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    migration_dir = ROOT / "src/main/resources/db/migrations"
    migration_paths = [migration_dir / name for name in MIGRATIONS]
    missing = [str(path.relative_to(ROOT)) for path in migration_paths if not path.is_file()]
    if missing:
        raise FileNotFoundError(f"missing migration files: {missing}")

    container = f"nyc-review-bootstrap-{uuid.uuid4().hex[:10]}"
    created = False
    try:
        run(
            [
                "docker",
                "run",
                "--detach",
                "--name",
                container,
                "--label",
                "nyc-review.purpose=bootstrap-schema-builder",
                "--network",
                "none",
                "--tmpfs",
                "/var/lib/mysql:rw,nosuid,size=1536m" if args.verify_dataset else "/var/lib/mysql:rw,nosuid,size=768m",
                "--env",
                f"MYSQL_ROOT_PASSWORD={PASSWORD}",
                "--env",
                f"MYSQL_DATABASE={DATABASE}",
                "--health-cmd",
                f"mysqladmin ping -h 127.0.0.1 -uroot -p{PASSWORD} --silent",
                "--health-interval",
                "1s",
                "--health-timeout",
                "3s",
                "--health-retries",
                "60",
                IMAGE,
                "--default-time-zone=+00:00",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_general_ci",
            ]
        )
        created = True
        wait_until_healthy(container)

        for path in migration_paths:
            apply_sql(container, path)

        dump = run(
            [
                "docker",
                "exec",
                container,
                "mysqldump",
                "-uroot",
                f"-p{PASSWORD}",
                "--no-data",
                "--skip-comments",
                "--skip-dump-date",
                "--skip-add-locks",
                "--set-gtid-purged=OFF",
                "--column-statistics=0",
                DATABASE,
            ]
        ).stdout.decode("utf-8")
        OUTPUT.write_text(normalize_dump(dump), encoding="utf-8")
        print(f"Generated {OUTPUT.relative_to(ROOT)}")
        if args.verify_dataset:
            verify_dataset(container, args.verify_dataset.resolve())
    finally:
        if created:
            subprocess.run(
                ["docker", "rm", "--force", container],
                cwd=ROOT,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                check=False,
            )


if __name__ == "__main__":
    main()
