-- NYC Review current empty database schema.
-- Generated by scripts/db/build_bootstrap_schema.py; do not edit manually.
-- Runtime datasets and neighborhood projections are imported separately.

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
DROP TABLE IF EXISTS `tb_agent_action_audit`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_agent_action_audit` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `run_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `action_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `action_type` varchar(48) COLLATE utf8mb4_general_ci NOT NULL,
  `status` varchar(24) COLLATE utf8mb4_general_ci NOT NULL,
  `request_json` json NOT NULL,
  `result_json` json DEFAULT NULL,
  `error_message` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_action_user_action` (`user_id`,`action_id`),
  KEY `idx_agent_action_run` (`run_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_agent_user_memory`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_agent_user_memory` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `memory_key` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `memory_value` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `source` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'favorite',
  `confidence` decimal(4,3) NOT NULL DEFAULT '1.000',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_agent_memory_user_key` (`user_id`,`memory_key`),
  KEY `idx_agent_memory_user_time` (`user_id`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_blog`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_blog` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` bigint NOT NULL COMMENT '商户id',
  `user_id` bigint unsigned NOT NULL COMMENT '用户id',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `images` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '探店的照片',
  `content` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '探店的文字描述',
  `liked` int unsigned DEFAULT '0' COMMENT '点赞数量',
  `comments` int unsigned NOT NULL DEFAULT '0' COMMENT '评论数量',
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEGACY',
  `data_version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_blog_comments`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_blog_comments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint unsigned NOT NULL COMMENT '用户id',
  `blog_id` bigint unsigned NOT NULL COMMENT '探店id',
  `parent_id` bigint unsigned NOT NULL COMMENT '关联的1级评论id',
  `answer_id` bigint unsigned NOT NULL COMMENT '回复的评论id',
  `content` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '回复的内容',
  `liked` int unsigned DEFAULT NULL COMMENT '点赞数',
  `status` tinyint unsigned DEFAULT NULL COMMENT '状态',
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEGACY',
  `data_version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_blog_comments_blog_time` (`blog_id`,`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_borough_shop_count`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_borough_shop_count` (
  `data_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `borough` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `type_id` bigint unsigned NOT NULL,
  `shop_count` int unsigned NOT NULL,
  `assigned_count` int unsigned NOT NULL,
  `unassigned_count` int unsigned NOT NULL,
  `centroid_x` double NOT NULL,
  `centroid_y` double NOT NULL,
  `min_x` double NOT NULL,
  `min_y` double NOT NULL,
  `max_x` double NOT NULL,
  `max_y` double NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`data_version`,`borough`,`type_id`),
  KEY `idx_borough_count_filter` (`data_version`,`type_id`,`borough`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_data_import`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_data_import` (
  `import_id` char(64) NOT NULL COMMENT 'dataset SHA-256',
  `data_version` varchar(32) NOT NULL,
  `profile` varchar(16) NOT NULL,
  `seed` bigint NOT NULL,
  `dataset_sha256` char(64) NOT NULL,
  `shop_count` int unsigned NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `imported_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`import_id`),
  UNIQUE KEY `uk_data_import_sha256` (`dataset_sha256`),
  KEY `idx_data_import_active` (`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_follow`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_follow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint unsigned NOT NULL COMMENT '用户id',
  `follow_user_id` bigint unsigned NOT NULL COMMENT '关联的用户id',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_follow_user_pair` (`user_id`,`follow_user_id`) USING BTREE,
  KEY `idx_follow_target` (`follow_user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_map_data_import`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_map_data_import` (
  `dataset_sha256` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `data_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `shop_ids_sha256` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `nta_source_sha256` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `nta_source_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `shop_count` int unsigned NOT NULL,
  `assigned_count` int unsigned NOT NULL,
  `unassigned_count` int unsigned NOT NULL,
  `assignment_methods` json NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `imported_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`dataset_sha256`,`nta_source_sha256`),
  KEY `idx_map_import_active` (`active`,`data_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_neighborhood`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_neighborhood` (
  `code` varchar(8) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Official 2020 NTA code',
  `name` varchar(160) COLLATE utf8mb4_general_ci NOT NULL,
  `borough` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `nta_type` varchar(8) COLLATE utf8mb4_general_ci NOT NULL COMMENT '0=residential; 9=special/non-residential in the source dataset',
  `cdta_code` varchar(8) COLLATE utf8mb4_general_ci NOT NULL,
  `centroid_x` double NOT NULL COMMENT 'Longitude used for the low-zoom count marker',
  `centroid_y` double NOT NULL COMMENT 'Latitude used for the low-zoom count marker',
  `min_x` double NOT NULL,
  `min_y` double NOT NULL,
  `max_x` double NOT NULL,
  `max_y` double NOT NULL,
  `boundary` multipolygon NOT NULL /*!80003 SRID 4326 */,
  `source_dataset_id` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `source_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `source_url` varchar(768) COLLATE utf8mb4_general_ci NOT NULL,
  `source_revision_date` date NOT NULL,
  `source_fetched_at` datetime NOT NULL,
  `source_sha256` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`code`),
  KEY `idx_neighborhood_borough_name` (`borough`,`name`),
  KEY `idx_neighborhood_source` (`source_dataset_id`,`source_version`),
  SPATIAL KEY `idx_neighborhood_boundary` (`boundary`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_neighborhood_alias`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_neighborhood_alias` (
  `borough` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `alias` varchar(160) COLLATE utf8mb4_general_ci NOT NULL,
  `neighborhood_code` varchar(8) COLLATE utf8mb4_general_ci NOT NULL,
  `alias_type` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'OFFICIAL or LEGACY_AREA',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`borough`,`alias`,`neighborhood_code`),
  KEY `idx_neighborhood_alias_code` (`neighborhood_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_neighborhood_shop_count`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_neighborhood_shop_count` (
  `data_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `neighborhood_code` varchar(8) COLLATE utf8mb4_general_ci NOT NULL,
  `type_id` bigint unsigned NOT NULL,
  `shop_count` int unsigned NOT NULL,
  `centroid_x` double NOT NULL,
  `centroid_y` double NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`data_version`,`neighborhood_code`,`type_id`),
  KEY `idx_neighborhood_count_filter` (`data_version`,`type_id`,`neighborhood_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_saved_itinerary`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_saved_itinerary` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `run_id` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `title` varchar(120) COLLATE utf8mb4_general_ci NOT NULL,
  `content_json` json NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_saved_itinerary_user_run` (`user_id`,`run_id`),
  KEY `idx_saved_itinerary_user_time` (`user_id`,`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_seckill_reminder`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_seckill_reminder` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `voucher_id` bigint unsigned NOT NULL,
  `remind_at` datetime NOT NULL,
  `status` varchar(24) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'PENDING',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_seckill_reminder_user_voucher` (`user_id`,`voucher_id`),
  KEY `idx_seckill_reminder_due` (`status`,`remind_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_seckill_voucher`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_seckill_voucher` (
  `voucher_id` bigint unsigned NOT NULL COMMENT '关联的优惠券的id',
  `stock` int NOT NULL COMMENT '库存',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `begin_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '生效时间',
  `end_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '失效时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`voucher_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT COMMENT='秒杀优惠券表';
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '商铺名称',
  `type_id` bigint unsigned NOT NULL COMMENT '商铺类型的id',
  `subcategory_id` bigint unsigned DEFAULT NULL,
  `images` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Compatibility projection of ordered resolved image URLs',
  `area` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '商圈',
  `legacy_area` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `neighborhood_code` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `borough` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '地址',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'Resolved merchant description',
  `x` double NOT NULL COMMENT 'longitude',
  `y` double NOT NULL COMMENT 'latitude',
  `avg_price` bigint unsigned DEFAULT NULL COMMENT '均价',
  `price_level` tinyint unsigned DEFAULT NULL,
  `sold` int(10) unsigned zerofill NOT NULL COMMENT '销量',
  `comments` int(10) unsigned zerofill NOT NULL COMMENT '评论数量',
  `local_review_count` int unsigned NOT NULL DEFAULT '0',
  `score` int unsigned DEFAULT NULL COMMENT 'Rating multiplied by 10; NULL when the public source provides no rating',
  `local_score` int unsigned DEFAULT NULL,
  `open_hours` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '营业时间',
  `phone` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `website` text COLLATE utf8mb4_general_ci,
  `reservation_url` text COLLATE utf8mb4_general_ci,
  `business_status` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'OPERATIONAL',
  `rating_count` int unsigned DEFAULT NULL,
  `external_score` int unsigned DEFAULT NULL,
  `external_rating_count` int unsigned DEFAULT NULL,
  `price_range_text` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `health_grade` varchar(8) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `last_enriched_at` datetime DEFAULT NULL,
  `timezone` varchar(64) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'America/New_York',
  `source_type` varchar(16) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEGACY',
  `external_id` varchar(160) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `source_name` varchar(160) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `source_url` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT 'Public source page for the merchant identity',
  `source_fetched_at` datetime DEFAULT NULL,
  `synthetic_fields` json DEFAULT NULL,
  `data_version` varchar(32) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_shop_source_external` (`source_type`,`external_id`),
  KEY `foreign_key_type` (`type_id`) USING BTREE,
  KEY `idx_shop_subcategory` (`subcategory_id`),
  KEY `idx_shop_data_version` (`data_version`),
  KEY `idx_shop_area_type` (`area`,`type_id`),
  KEY `idx_shop_source_type` (`source_type`),
  KEY `idx_shop_source_fetched_at` (`source_fetched_at`),
  KEY `idx_shop_map_filter` (`data_version`,`type_id`,`neighborhood_code`,`x`,`y`),
  KEY `idx_shop_status_type` (`business_status`,`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_business_hours`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_business_hours` (
  `shop_id` bigint unsigned NOT NULL,
  `day_of_week` tinyint unsigned NOT NULL COMMENT '1=Monday, 7=Sunday',
  `closed` tinyint(1) NOT NULL DEFAULT '0',
  `open_time` time DEFAULT NULL,
  `close_time` time DEFAULT NULL,
  `closes_next_day` tinyint(1) NOT NULL DEFAULT '0',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`shop_id`,`day_of_week`),
  KEY `idx_shop_hours_day` (`day_of_week`,`closed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_favorite`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_favorite` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `shop_id` bigint unsigned NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_favorite_user_shop` (`user_id`,`shop_id`),
  KEY `idx_shop_favorite_user_time` (`user_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_field_observation`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_field_observation` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shop_id` bigint unsigned NOT NULL,
  `field_name` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `value_json` json NOT NULL,
  `provider` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `external_id` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `observed_at` datetime NOT NULL,
  `expires_at` datetime DEFAULT NULL,
  `match_score` decimal(6,5) NOT NULL,
  `source_priority` smallint unsigned NOT NULL,
  `content_sha256` char(64) COLLATE utf8mb4_general_ci NOT NULL,
  `snapshot_version` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_field_observation` (`shop_id`,`field_name`,`provider`,`content_sha256`),
  KEY `idx_field_observation_resolve` (`shop_id`,`field_name`,`source_priority`,`observed_at`),
  KEY `idx_field_observation_snapshot` (`snapshot_version`,`provider`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_image`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_image` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shop_id` bigint unsigned NOT NULL,
  `display_url` text COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Resolved attributed merchant-specific or fallback image URL',
  `source_page_url` text COLLATE utf8mb4_general_ci COMMENT 'Attribution or source page rather than only the image bytes',
  `source_name` varchar(160) COLLATE utf8mb4_general_ci NOT NULL,
  `author_name` varchar(160) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `license_name` varchar(80) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `license_url` text COLLATE utf8mb4_general_ci,
  `image_type` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'ILLUSTRATIVE',
  `match_type` varchar(32) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'CATEGORY_FALLBACK',
  `is_primary` tinyint(1) NOT NULL DEFAULT '0',
  `display_order` smallint unsigned NOT NULL DEFAULT '0',
  `width` int unsigned DEFAULT NULL,
  `height` int unsigned DEFAULT NULL,
  `content_sha256` char(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `last_checked_at` datetime DEFAULT NULL,
  `availability_status` varchar(24) COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'AVAILABLE',
  `cached_url` text COLLATE utf8mb4_general_ci,
  `sha256` char(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sort_order` tinyint unsigned NOT NULL DEFAULT '0',
  `fetched_at` datetime DEFAULT NULL,
  `data_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_image_order` (`shop_id`,`data_version`,`sort_order`),
  KEY `idx_shop_image_shop` (`shop_id`,`sort_order`),
  KEY `idx_shop_image_version_type` (`data_version`,`image_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_map_location`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_map_location` (
  `shop_id` bigint unsigned NOT NULL,
  `data_version` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `location` point NOT NULL /*!80003 SRID 4326 */,
  `neighborhood_code` varchar(8) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `assignment_method` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'POINT_IN_POLYGON or UNASSIGNED',
  `source_area` varchar(128) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'Original friendly area; Agent semantics continue to use tb_shop.area',
  `assigned_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`data_version`,`shop_id`),
  KEY `idx_shop_map_neighborhood` (`data_version`,`neighborhood_code`,`shop_id`),
  SPATIAL KEY `idx_shop_map_location` (`location`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_review`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_review` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` bigint unsigned NOT NULL COMMENT '店铺id',
  `root_id` bigint unsigned DEFAULT NULL,
  `parent_id` bigint unsigned DEFAULT NULL,
  `depth` tinyint unsigned NOT NULL DEFAULT '0',
  `author_role` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'USER',
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEGACY',
  `language` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `sentiment` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `topic_tags` json DEFAULT NULL,
  `security_test` tinyint(1) NOT NULL DEFAULT '0',
  `user_id` bigint unsigned NOT NULL COMMENT '用户id',
  `reply_to_user_id` bigint unsigned DEFAULT NULL,
  `rating` tinyint unsigned DEFAULT NULL COMMENT '1-5 for depth-0 reviews; NULL for replies',
  `content` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `images` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '评价图片',
  `liked` int unsigned DEFAULT '0' COMMENT '点赞数',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_shop_id` (`shop_id`) USING BTREE,
  KEY `idx_shop_review_roots` (`shop_id`,`parent_id`,`create_time`),
  KEY `idx_shop_review_thread` (`root_id`,`depth`,`create_time`),
  CONSTRAINT `chk_shop_review_depth` CHECK ((`depth` between 0 and 2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_review_like`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_review_like` (
  `review_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`,`user_id`),
  KEY `idx_shop_review_like_user` (`user_id`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_source_match`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_source_match` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `shop_id` bigint unsigned NOT NULL,
  `provider` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `external_id` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `source_url` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `matched_fields` json NOT NULL,
  `match_score` decimal(6,5) NOT NULL,
  `match_method` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `observed_at` datetime NOT NULL,
  `snapshot_version` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_source_match` (`shop_id`,`provider`,`external_id`,`snapshot_version`),
  KEY `idx_source_match_provider_external` (`provider`,`external_id`),
  KEY `idx_source_match_shop_active` (`shop_id`,`active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_subcategory`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_subcategory` (
  `id` bigint unsigned NOT NULL,
  `type_id` bigint unsigned NOT NULL,
  `name` varchar(64) NOT NULL,
  `slug` varchar(64) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_shop_subcategory_slug` (`type_id`,`slug`),
  KEY `idx_shop_subcategory_type` (`type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_tag`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_tag` (
  `shop_id` bigint unsigned NOT NULL,
  `tag` varchar(64) NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`shop_id`,`tag`),
  KEY `idx_shop_tag_tag` (`tag`,`shop_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_shop_type`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_shop_type` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '类型名称',
  `slug` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '图标',
  `sort` int unsigned DEFAULT NULL COMMENT '顺序',
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_user`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_user` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `phone` varchar(20) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'Canonical E.164 phone number',
  `password` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'BCrypt or transitional legacy password hash',
  `recovery_key_hash` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'BCrypt recovery-key hash',
  `nick_name` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '昵称',
  `icon` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '人物头像',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_user_phone` (`phone`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_user_info`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_user_info` (
  `user_id` bigint unsigned NOT NULL COMMENT '主键，用户id',
  `city` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT '' COMMENT '城市名称',
  `introduce` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '个人介绍',
  `fans` int unsigned DEFAULT '0' COMMENT '粉丝数量',
  `followee` int unsigned DEFAULT '0' COMMENT '关注的人的数量',
  `gender` tinyint unsigned DEFAULT '0' COMMENT '性别',
  `birthday` date DEFAULT NULL COMMENT '生日',
  `credits` int unsigned DEFAULT '0' COMMENT '积分',
  `level` tinyint unsigned DEFAULT '0' COMMENT '会员级别',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`user_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_voucher`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_voucher` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `shop_id` bigint unsigned DEFAULT NULL COMMENT '商铺id',
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '代金券标题',
  `sub_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '副标题',
  `rules` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '使用规则',
  `pay_value` bigint unsigned NOT NULL COMMENT '支付金额',
  `actual_value` bigint NOT NULL COMMENT '抵扣金额',
  `type` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '0,普通券；1,秒杀券',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '1,上架; 2,下架; 3,过期',
  `valid_days` smallint unsigned NOT NULL DEFAULT '30' COMMENT 'Days valid after acquisition',
  `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'LEGACY',
  `data_version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
DROP TABLE IF EXISTS `tb_voucher_order`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `tb_voucher_order` (
  `id` bigint NOT NULL COMMENT '主键',
  `user_id` bigint unsigned NOT NULL COMMENT '下单的用户id',
  `voucher_id` bigint unsigned NOT NULL COMMENT '购买的代金券id',
  `pay_type` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '支付方式',
  `status` tinyint unsigned NOT NULL DEFAULT '1' COMMENT '订单状态',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '下单时间',
  `expires_at` datetime DEFAULT NULL COMMENT 'Coupon ownership expiration time',
  `pay_time` timestamp NULL DEFAULT NULL COMMENT '支付时间',
  `use_time` timestamp NULL DEFAULT NULL COMMENT '核销时间',
  `refund_time` timestamp NULL DEFAULT NULL COMMENT '退款时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_voucher_order_user_voucher` (`user_id`,`voucher_id`),
  KEY `idx_voucher_order_user_expiry` (`user_id`,`expires_at`,`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
